version: 2

jobs:
  fmtcheck:
    docker:
      - image: hashicorp/terraform:0.12.16

    steps:
      - checkout

      - run:
          name: Check Format
          command: |
            terraform fmt -recursive -check=true
  lint:
    docker:
      - image: wata727/tflint:0.12.1

    steps:
      - checkout

      - run:
          name: Check Lint
          command: |
            tflint modules/glue
            tflint modules/iam
            tflint modules/emr

workflows:
  version: 2
  check:
    jobs:
      - fmtcheck
      - lint
